# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Jurin Katayama Flores
description: Applied Economist & Policy Analyst
baseurl: ""
url: "https://jurinkflores.github.io"
og_image: /assets/img/profile-pic.jpg

header:
  pages:
    - name: Home
      slug: /
    - name: Consulting
    # - name: Blog

footer:
  show_powered_by: true
  contact:
    - type: linkedin
      name: LinkedIn
      link: http://linkedin.com/in/jurin-katayama-flores
    - type: github
      name: GitHub
      link: http://github.com/jurinkflores

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
